build: add gen-csv files in downstream repo
red-hat-storage/rook pull request #581
Opened 2024-02-28 05:37 UTC by subhamkrai

build: add gen-csv files in downstream repo

This commit add the csv related changes to downstream and
later will be removed from upstream also renaming make 'csv'
to 'gen-csv' and also adds validation check in ci to verify
right files are modified.

build: these are auto-generated files

This commit contains auto-generated files
that are added/modified by running 'make gen-csv'.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-02-28 05:39 UTC, subhamkrai commented
@travisn @Nikhil-Ladha PTAL

2024-03-04 06:20 UTC, Nikhil-Ladha commented
cc @iamniting

2024-03-05 16:37 UTC, BlaineEXE commented
I am also somewhat concerned that this code is special for downstream and that it may be erased when github.com/rook/rook@master is resynced here, or to release-\* branches. I certainly may also be misunderstanding something here.

2024-03-06 06:08 UTC, subhamkrai commented
> I am also somewhat concerned that this code is special for downstream and that it may be erased when github.com/rook/rook@master is resynced here, or to release-* branches. I certainly may also be misunderstanding something here.

If we just skip one upstream commit that removes the csv related file, downstream should be good then I guess

2024-03-06 08:32 UTC, Nikhil-Ladha commented
> > I am also somewhat concerned that this code is special for downstream and that it may be erased when github.com/rook/rook@master is resynced here, or to release-* branches. I certainly may also be misunderstanding something here.
> 
> If we just skip one upstream commit that removes the csv related file, downstream should be good then I guess

We don't have to skip anything as such, once we are set to merge these changes at that time we should first delete the changes in upstream, sync those changes to downstream, rebase this PR and then merge. Then, everything should be good and we won't be facing any challenges.

And, later syncs won't be a problem because we are just bring commits from upstream to downstream, that would continue as usual.

2024-03-06 10:33 UTC, subhamkrai commented
> > > I am also somewhat concerned that this code is special for downstream and that it may be erased when github.com/rook/rook@master is resynced here, or to release-* branches. I certainly may also be misunderstanding something here.
> > 
> > 
> > If we just skip one upstream commit that removes the csv related file, downstream should be good then I guess
> 
> We don't have to skip anything as such, once we are set to merge these changes at that time we should first delete the changes in upstream, sync those changes to downstream, rebase this PR and then merge. Then, everything should be good and we won't be facing any challenges.
> 
> And, later syncs won't be a problem because we are just bring commits from upstream to downstream, that would continue as usual.

IIRC, once we remove the csv generation files from upstream and sync that to downstream those file will be removed in downstream also and the csv generation will fail. But let's sync on this @Nikhil-Ladha

2024-03-14 05:49 UTC, parth-gr commented
@subhamkrai in last offline discussion we suggested to have a separate readme.md that only talks about downstream specific changes and avoid merge conflicts.
Currently this change and change for SVG is added https://github.com/red-hat-storage/rook/pull/589
So with this change have a plan to initiate that

cc @travisn @iamniting

2024-03-14 05:53 UTC, iamniting commented
> @subhamkrai in last offline discussion we suggested to have a separate readme.md that only talks about downstream specific changes and avoid merge conflicts. Currently this change and change for SVG is added #589 So with this PR have a plan to initiate that
> 
> cc @travisn @iamniting

I would highly suggest doing so, so that we don't miss any commits in the future branches.

2024-03-15 05:59 UTC, subhamkrai commented
> > @subhamkrai in last offline discussion we suggested to have a separate readme.md that only talks about downstream specific changes and avoid merge conflicts. Currently this change and change for SVG is added #589 So with this PR have a plan to initiate that
> > cc @travisn @iamniting
> 
> I would highly suggest doing so, so that we don't miss any commits in the future branches.

I will prefer to do it in separate PR
since I'm planning to get this PR merged EOD and docs PRs generally have more reviews before they get merged

2024-03-15 06:31 UTC, parth-gr commented
> I will prefer to do it in separate PR since I'm planning to get this PR merged EOD and docs PRs generally have more reviews before they get merged

I don't have any problem with separate PR, but keep that item in mind as we cant track it separately anywhere.

2024-03-18 06:16 UTC, Nikhil-Ladha commented on build/csv/rook-ceph.clusterserviceversion.yaml
> +      operated-by: rookoperator
Update these fields as per ocs-operator csv

2024-03-18 06:17 UTC, Nikhil-Ladha commented on build/csv/rook-ceph.clusterserviceversion.yaml
> +  minKubeVersion: 1.10.0
Please update these fields as per the ocs-operator CSV

2024-03-18 12:35 UTC, subhamkrai commented
@iamniting PTAL

2024-03-18 13:39 UTC, iamniting requested changes

2024-03-18 13:39 UTC, iamniting commented on build/csv/rook-ceph.clusterserviceversion.yaml
> +    name: Provider Name
Can you update this as well?

2024-03-19 09:51 UTC, subhamkrai commented on deploy/examples/operator-openshift.yaml
> +                  name: ocs-operator-config
@iamniting added the field

2024-03-19 09:54 UTC, iamniting commented on deploy/examples/operator-openshift.yaml
> +                  name: ocs-operator-config
looks good

2024-03-19 13:46 UTC, iamniting commented
CSV changes looks good to me

2024-03-20 10:51 UTC, sp98 commented
/approve

2024-03-20 10:53 UTC, merged