external: add a new configmap to store external cluster script
red-hat-storage/rook pull request #729
Opened 2024-09-13 12:31 UTC by Nikhil-Ladha

Added a new static configmap to store the external cluster script and ship it as part of the rook bundle.

2024-09-13 17:47 UTC, travisn reviewed
Let's ensure the Rook CI will fail a gen-csv check so when the auto-sync PRs update the branch, we can detect when this needs to be refreshed.

2024-09-17 06:23 UTC, Nikhil-Ladha commented
> Let's ensure the Rook CI will fail a gen-csv check so when the auto-sync PRs update the branch, we can detect when this needs to be refreshed.

We already have this [check](https://github.com/red-hat-storage/rook/blob/master/.github/workflows/build.yml#L101) introduced when we created a separate CSV/bundle for rook long back.

2024-09-17 10:34 UTC, parth-gr requested changes

2024-09-17 10:39 UTC, Nikhil-Ladha commented on deploy/examples/external-cluster-script-configmap.yaml
> +apiVersion: v1
1. We are going to remove it from the annotation in the next release.
2. What do you mean by CLI? The UI team will do the UI change, we have respective stories for that.

2024-09-17 10:50 UTC, parth-gr commented on deploy/examples/external-cluster-script-configmap.yaml
> +apiVersion: v1
>We are going to remove it from the annotation in the next release.
Ok thanks, So lets track down it somewhere or maybe we can have that removal in master too.

>What do you mean by CLI?
Update the documentation

2024-09-17 12:14 UTC, Nikhil-Ladha commented on deploy/examples/external-cluster-script-configmap.yaml
> +apiVersion: v1
We have the stories for all the changes, please take a look once and let me know if we are missing anything.

2024-09-17 13:48 UTC, Nikhil-Ladha commented on deploy/examples/kustomization.yaml
> +  - external-cluster-script-configmap.yaml
Yeah, just tested it out. The cm is getting created when the rook bundle is installed on the cluster.

2024-09-17 13:52 UTC, parth-gr commented
/lgtm

2024-09-17 13:52 UTC, parth-gr commented on deploy/examples/kustomization.yaml
> +  - external-cluster-script-configmap.yaml
Please update the result in the PR

2024-09-19 06:29 UTC, Nikhil-Ladha commented
@travisn if everything looks good can we merge this PR?

2024-09-19 17:42 UTC, travisn commented
/approve
/lgtm

2024-09-19 17:43 UTC, merged